// Generated by jextract

package cn.solarmoon.sparkcore.api.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct slice_ref_uint8 {
 *     const uint8_t *ptr;
 *     size_t len;
 * } slice_ref_uint8_t
 * }
 */
public class slice_ref_uint8_t extends slice_ref_uint8 {

    slice_ref_uint8_t() {
        // Should not be called directly
    }
}

