/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_SPARK_CORE_GEOMETRY_FFI__
#define __RUST_SPARK_CORE_GEOMETRY_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** <No documentation available> */
typedef struct CAnimationFile CAnimationFile_t;

/** <No documentation available> */
void
free_animation_file (
    CAnimationFile_t * anim);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_uint8_t;

/** <No documentation available> */
CAnimationFile_t *
load_animation_file (
    slice_ref_uint8_t json_bytes);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_SPARK_CORE_GEOMETRY_FFI__ */
